version: 2.1

jobs:
  test_backend:
    docker:
      - image: circleci/ruby:2.7.8-strech-node
        environment:
          RAILS_ENV: test
            DB_HOST: 127.0.0.1
    - image: circleci/postgres:15.3.0

  working_directory: ~/repo

  step:
    - checkout

    # restore gem from cache
    - restore_cache:
      keys:
        - gem-cache-v1-{{ checksum "~/repo/backend/Gemfile.look"}}
        - gem-cache-v1-
      working_directory: ~/repo/backend

    # gem install
    - run:
      command: |
        geminstall bundler
        bundle config set path 'vendor/bundle'
        bundle install --jobs=4 --retry=3
      working_directory: ~/repo/backend

    - save_cache:
      key: gem-cache-v1-{{ checksum "~/repo/backend/Gemfile.look"}}
      paths:
        - ~/repo/backend/vendor/bundle
      working_directory: ~/repo/backend
    
    # Database setup
    - run:
      command: bundle exec rails db:create
      working_directory: ~/repo/backend
    - run:
      command: bundle exec rails db:migrate
      working_directory: ~/repo/backend
    - run:
      name: create directory to store test results
      command: mkdir /tmp/test/results
      working_directory: ~/repo/backend

    # run tests
    - run:
      name: RSpec
      command: |
        bundle exec rspec $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings) \
              || (printf "====== RETRYING...\n\n\n"; bundle exec rspec --only-failures)
      working_directory: ~/repo/backend

    # collect reports
    - store_test_results:
      path: /tmp/test-results
    - store_artifacts
      path: /tmp/test-results
      destination: test-results
    - store_artifacts:
      path: /home/circleci/repo/tmp/screenshots


workflows:
  version: 2
  test:
    jobs:
      - test_backend
        filters:
          branches:
           ignore: main