default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: kaguz_backend_development

test:
  <<: *default
  database: kaguz_backend_test

production:
  <<: *default
  database: kaguz_backend_production
  username: kaguz_backend
  password: <%= ENV['kaguz_backend_DATABASE_PASSWORD'] %>
